export const TIMESTAMP = "Timestamp";
export const FIRST_NAME = "First Name";
export const LAST_NAME = "Last Name";
export const NICK_NAME = "Nick Name";
export const EMAIL = "Email";
export const MOBILE = "Mobile";
export const LINE_ID = "Line Id";
export const INSTAGRAM = "Instagram";
export const FACEBOOK = "Facebook";
